version: "3"
services:
  # ngrok-tails-server:
  #   image: wernight/ngrok
  #   networks:
  #     - tails-server
  #   ports:
  #     - 4044:4040
  #   command: ngrok http tails-server:6543 --log stdout
  tails-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.tails-server
    volumes:
      - ../server_tails_files:/home/indy/storage
    ports:
      - 6543:6543
    networks:
      - tails-server
    privileged: true
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path storage
  # tester:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.test
networks:
  tails-server:
